name: docs
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # Check out the branch that triggered this workflow to the 'source' subdirectory
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: master
          path: source
      - name: install DocFX
        run: "dotnet tool install -g docfx"
      - name: Build docs
        run: "docfx docfx/docfx.json"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docfx/_site
